// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void screen1_key(lv_event_t * e);
void rotation_screen(lv_event_t * e);
void TextInput1(lv_event_t * e);
void TextInput2(lv_event_t * e);
void keyboardValue(lv_event_t * e);
void configwifi_key(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
