// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_configwifi_screen_init(void)
{
    ui_configwifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_configwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_configwifi, lv_color_hex(0xE3FCE2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_configwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_configwifi);
    lv_obj_set_width(ui_TextArea1, 200);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TextArea1, 70);
    lv_obj_set_y(ui_TextArea1, 59);
    lv_textarea_set_text(ui_TextArea1, "QMYD2.4G");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_textarea_set_one_line(ui_TextArea1, true);



    ui_TextArea2 = lv_textarea_create(ui_configwifi);
    lv_obj_set_width(ui_TextArea2, 200);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TextArea2, 70);
    lv_obj_set_y(ui_TextArea2, 112);
    lv_textarea_set_text(ui_TextArea2, "QMYD13286306350");
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_textarea_set_password_mode(ui_TextArea2, true);



    ui_Label3 = lv_label_create(ui_configwifi);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -126);
    lv_obj_set_y(ui_Label3, -166);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "WIFI:");

    ui_Label4 = lv_label_create(ui_configwifi);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -127);
    lv_obj_set_y(ui_Label4, -112);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "PSW:");

    ui_Keyboard1 = lv_keyboard_create(ui_configwifi);
    lv_obj_set_width(ui_Keyboard1, 318);
    lv_obj_set_height(ui_Keyboard1, 169);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Button3 = lv_btn_create(ui_configwifi);
    lv_obj_set_width(ui_Button3, 200);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -1);
    lv_obj_set_y(ui_Button3, 200);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_configwifi);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -3);
    lv_obj_set_y(ui_Label5, 202);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "开始配网");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configwifi, ui_event_configwifi, LV_EVENT_ALL, NULL);

}
