// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
// SCREEN: ui_configwifi
void ui_configwifi_screen_init(void);
void ui_event_configwifi(lv_event_t * e);
extern lv_obj_t * ui_configwifi;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_daobai_icon_png);    // assets/daobai_icon.png



LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);
LV_FONT_DECLARE(ui_font_Font22);
LV_FONT_DECLARE(ui_font_Font32);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
